version: '3.7'

services:
  drone-server:
    image: drone/drone:1.6.2
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/lib/drone:/data
    environment:
      DRONE_AGENTS_ENABLED: "true"
      DRONE_BITBUCKET_CLIENT_ID: ${DRONE_BITBUCKET_CLIENT_ID}
      DRONE_BITBUCKET_CLIENT_SECRET: ${DRONE_BITBUCKET_CLIENT_SECRET}
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_SERVER_HOST: ${SERVER_HOST}
      DRONE_SERVER_PROTO: http

  drone-runner:
    image: drone/drone-runner-docker:1
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DRONE_RPC_PROTO: http
      DRONE_RPC_HOST: ${SERVER_HOST}
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_RUNNER_CAPACITY: 3
