version: '3.7'

networks:
  default:
    external:
      name: reverse_proxy

services:
  drone-server:
    image: drone/drone:1.6.2
    name: "drone_server"
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/lib/drone:/data
    environment:
      DRONE_AGENTS_ENABLED: "true"
      DRONE_BITBUCKET_CLIENT_ID: ${DRONE_BITBUCKET_CLIENT_ID}
      DRONE_BITBUCKET_CLIENT_SECRET: ${DRONE_BITBUCKET_CLIENT_SECRET}
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_SERVER_HOST: ${SERVER_HOST}
      DRONE_SERVER_PROTO: http

    drone-runner:
      image: drone/drone-runner-docker:1
      ports:
        - 3000:3000
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        DRONE_RPC_PROTO: http
        DRONE_RPC_HOST: ${SERVER_HOST}
        DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
        DRONE_RUNNER_CAPACITY: 3

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    build: ./
    container_name: nginx-proxy
    restart: unless-stopped
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - ${SERVER_HOST}:80:80
      - ${SERVER_HOST}:443:443
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    volumes:
      - /var/log/nginx:/var/log/nginx:rw
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./www:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped

    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./www:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

    depends_on:
      - nginx-proxy